### PR TITLE
make ubuntu a docker build for ffmpeg5

### PR DESCRIPTION
**Pull request by chincheta0815**
does that help?
I uses Docker for the ffmpeg5 compile...

Only issue: docker/docker-build-x86.sh does not compile it due to some errors in the rust compile...
Probablyyou are better in rust than me.

### CODE REVIEW

**Comment by CDrummond** [comment]
So, this pull does not actually work? What are the errors?

**Comment by chincheta0815** [comment]
Okay. Stupid me. Forgot to apt-get clang...

Now I get another error:
``
2024-02-19T18:03:35.3564391Z    Compiling ndarray-stats v0.5.1
2024-02-19T18:03:36.4529383Z    Compiling crossbeam v0.8.2
2024-02-19T18:03:37.2802577Z error[E0004]: non-exhaustive patterns: `sys::AVPixelFormat::AV_PIX_FMT_P212BE`, `sys::AVPixelFormat::AV_PIX_FMT_P212LE`, `sys::AVPixelFormat::AV_PIX_FMT_P412BE` and 3 more not covered
2024-02-19T18:03:37.2806201Z     --> /build/cache/registry/src/index.crates.io-6f17d22bba15001f/ffmpeg-next-6.0.0/src/util/format/pixel.rs:467:15
2024-02-19T18:03:37.2808438Z      |
2024-02-19T18:03:37.2809295Z 467  |         match value {
2024-02-19T18:03:37.2810746Z      |               ^^^^^ patterns `sys::AVPixelFormat::AV_PIX_FMT_P212BE`, `sys::AVPixelFormat::AV_PIX_FMT_P212LE`, `sys::AVPixelFormat::AV_PIX_FMT_P412BE` and 3 more not covered
2024-02-19T18:03:37.2812283Z      |
2024-02-19T18:03:37.2813524Z note: `sys::AVPixelFormat` defined here
2024-02-19T18:03:37.2814875Z     --> /build/release/build/ffmpeg-sys-next-640db4da940885f2/out/bindings.rs:5924:1
2024-02-19T18:03:37.2815867Z      |
2024-02-19T18:03:37.2816271Z 5924 | pub enum AVPixelFormat {
2024-02-19T18:03:37.2817786Z      | ^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T18:03:37.2820205Z ...
2024-02-19T18:03:37.2850994Z 6148 |     AV_PIX_FMT_P212BE = 222,
2024-02-19T18:03:37.2851716Z      |     ----------------- not covered
2024-02-19T18:03:37.2852247Z 6149 |     AV_PIX_FMT_P212LE = 223,
2024-02-19T18:03:37.2852876Z      |     ----------------- not covered
2024-02-19T18:03:37.2853442Z 6150 |     AV_PIX_FMT_P412BE = 224,
2024-02-19T18:03:37.2854105Z      |     ----------------- not covered
2024-02-19T18:03:37.2854652Z 6151 |     AV_PIX_FMT_P412LE = 225,
2024-02-19T18:03:37.2855298Z      |     ----------------- not covered
2024-02-19T18:03:37.2855850Z 6152 |     AV_PIX_FMT_GBRAP14BE = 226,
2024-02-19T18:03:37.2856548Z      |     -------------------- not covered
2024-02-19T18:03:37.2857286Z      = note: the matched value is of type `sys::AVPixelFormat`
2024-02-19T18:03:37.2858676Z help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown, or multiple match arms
2024-02-19T18:03:37.2859936Z      |
2024-02-19T18:03:37.2860416Z 797  ~             AV_PIX_FMT_RGBAF32LE => Pixel::RGBAF32LE,
2024-02-19T18:03:37.2861029Z 798  ~             _ => todo!(),
2024-02-19T18:03:37.2861489Z      |
2024-02-19T18:03:37.2861704Z 
2024-02-19T18:03:37.2883670Z error[E0004]: non-exhaustive patterns: `sys::AVFrameSideDataType::AV_FRAME_DATA_VIDEO_HINT` not covered
2024-02-19T18:03:37.2891647Z     --> /build/cache/registry/src/index.crates.io-6f17d22bba15001f/ffmpeg-next-6.0.0/src/util/frame/side_data.rs:78:15
2024-02-19T18:03:37.2893029Z      |
2024-02-19T18:03:37.2931058Z 78   |         match value {
2024-02-19T18:03:37.2931910Z      |               ^^^^^ pattern `sys::AVFrameSideDataType::AV_FRAME_DATA_VIDEO_HINT` not covered
2024-02-19T18:03:37.2932750Z      |
2024-02-19T18:03:37.2933215Z note: `sys::AVFrameSideDataType` defined here
2024-02-19T18:03:37.2934373Z     --> /build/release/build/ffmpeg-sys-next-640db4da940885f2/out/bindings.rs:6874:1
2024-02-19T18:03:37.2935246Z      |
2024-02-19T18:03:37.2935648Z 6874 | pub enum AVFrameSideDataType {
2024-02-19T18:03:37.2936197Z      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19T18:03:37.2936668Z ...
2024-02-19T18:03:37.2937063Z 6902 |     AV_FRAME_DATA_VIDEO_HINT = 27,
2024-02-19T18:03:37.2937813Z      |     ------------------------ not covered
2024-02-19T18:03:37.2938586Z      = note: the matched value is of type `sys::AVFrameSideDataType`
2024-02-19T18:03:37.2940087Z help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
2024-02-19T18:03:37.2941341Z      |
2024-02-19T18:03:37.2942501Z 128  ~             AV_FRAME_DATA_AMBIENT_VIEWING_ENVIRONMENT => Type::AMBIENT_VIEWING_ENVIRONMENT,
2024-02-19T18:03:37.2944238Z 129  ~             sys::AVFrameSideDataType::AV_FRAME_DATA_VIDEO_HINT => todo!(),
2024-02-19T18:03:37.2945130Z      |
2024-02-19T18:03:37.2945333Z 
2024-02-19T18:03:37.4251916Z error[E0004]: non-exhaustive patterns: `sys::AVCodecID::AV_CODEC_ID_PDV`, `sys::AVCodecID::AV_CODEC_ID_EVC`, `sys::AVCodecID::AV_CODEC_ID_RTV1` and 4 more not covered
2024-02-19T18:03:37.4254432Z     --> /build/cache/registry/src/index.crates.io-6f17d22bba15001f/ffmpeg-next-6.0.0/src/codec/id.rs:664:15
2024-02-19T18:03:37.4258115Z      |
2024-02-19T18:03:37.4258527Z 664  |         match value {
2024-02-19T18:03:37.4263542Z      |               ^^^^^ patterns `sys::AVCodecID::AV_CODEC_ID_PDV`, `sys::AVCodecID::AV_CODEC_ID_EVC`, `sys::AVCodecID::AV_CODEC_ID_RTV1` and 4 more not covered
2024-02-19T18:03:37.4269989Z      |
2024-02-19T18:03:37.4275486Z note: `sys::AVCodecID` defined here
2024-02-19T18:03:37.4276760Z     --> /build/release/build/ffmpeg-sys-next-640db4da940885f2/out/bindings.rs:8214:1
2024-02-19T18:03:37.4277778Z      |
2024-02-19T18:03:37.4280662Z 8214 | pub enum AVCodecID {
2024-02-19T18:03:37.4286527Z      | ^^^^^^^^^^^^^^^^^^
2024-02-19T18:03:37.4286980Z ...
2024-02-19T18:03:37.4302770Z 8481 |     AV_CODEC_ID_PDV = 266,
2024-02-19T18:03:37.4303398Z      |     --------------- not covered
2024-02-19T18:03:37.4303894Z 8482 |     AV_CODEC_ID_EVC = 267,
2024-02-19T18:03:37.4304437Z      |     --------------- not covered
2024-02-19T18:03:37.4304929Z 8483 |     AV_CODEC_ID_RTV1 = 268,
2024-02-19T18:03:37.4305462Z      |     ---------------- not covered
2024-02-19T18:03:37.4305962Z 8484 |     AV_CODEC_ID_VMIX = 269,
2024-02-19T18:03:37.4306502Z      |     ---------------- not covered
2024-02-19T18:03:37.4306951Z ...
2024-02-19T18:03:37.4307282Z 8690 |     AV_CODEC_ID_AC4 = 86119,
2024-02-19T18:03:37.4307837Z      |     --------------- not covered
2024-02-19T18:03:37.4308464Z      = note: the matched value is of type `sys::AVCodecID`
2024-02-19T18:03:37.4309793Z help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown, or multiple match arms
2024-02-19T18:03:37.4310974Z      |
2024-02-19T18:03:37.4369634Z 1297 ~             AV_CODEC_ID_ANULL => Id::ANULL,
2024-02-19T18:03:37.4370392Z 1298 ~             _ => todo!(),
2024-02-19T18:03:37.4370850Z      |
2024-02-19T18:03:37.4371044Z 
2024-02-19T18:03:37.6970387Z For more information about this error, try `rustc --explain E0004`.
2024-02-19T18:03:37.7037169Z error: could not compile `ffmpeg-next` (lib) due to 3 previous errors
2024-02-19T18:03:37.7040932Z warning: build failed, waiting for other jobs to finish...
2024-02-19T18:04:12.5729284Z ##[error]Process completed with exit code 101.
2024-02-19T18:04:12.5815748Z Post job cleanup.
2024-02-19T18:04:12.6475317Z [command]/usr/bin/git version
2024-02-19T18:04:12.6508406Z git version 2.43.0
2024-02-19T18:04:12.6550778Z Temporarily overriding HOME='/home/runner/work/_temp/a5952f61-f023-4879-8ba4-c7a909b7ae82' before making global git config changes
2024-02-19T18:04:12.6552507Z Adding repository directory to the temporary git global config as a safe directory
2024-02-19T18:04:12.6556530Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/bliss-analyser/bliss-analyser
2024-02-19T18:04:12.6581743Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-02-19T18:04:12.6603036Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-02-19T18:04:12.6753169Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-02-19T18:04:12.6765654Z http.https://github.com/.extraheader
2024-02-19T18:04:12.6776655Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-02-19T18:04:12.6797017Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-02-19T18:04:12.7139237Z Cleaning up orphan processes
``

**Comment by CDrummond** [comment]
Looks like issues with ffmpeg. Is ffmpeg-next 5 or 6? Perhaps there is a need to explicitly specify? Been a while but I'm pretty sure its bliss-rs that pulls in ffmpeg-next

**Comment by chincheta0815** [comment]
indeed it seems to be bliss-audio...Probably simplay an updated Cargo.toml does the trick.Am 19.02.2024 um 19:17 schrieb CraigD ***@***.***>:﻿
Looks like issues with ffmpeg. Is ffmpeg-next 5 or 6? Perhaps there is a need to explicitly specify? Been a while but I'm pretty sure its bliss-rs that pulls in ffmpeg-next

**Comment by chincheta0815** [comment]
all checkmarks are green now.
issues was to update bliss-audio to the latest version.

**Comment by CDrummond** [comment]
Great! Thanks for working on this.

**Pull request merged**
